server:
  port: 8762
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.1:3306/mysql?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password:


  mybatis:
    #config-locations: mybatis/mybatis-config.xml
    mapper-locations: mybatis/*.xml
    type-aliases-package: com.peachcake.mapper


  redis:
    #    host: 192.168.223.131
    #    port: 7001
    password: 123456
    # Redis 默认数据库设置
    database: 0
    # Redis Cluster集群节点配置
    cluster:
      # Redis 集群地址信息
      nodes:
        - 192.168.10.4:6379
        - 192.168.10.7:6379
        - 192.168.10.9:6379
        - 192.168.10.10:6379
        - 192.168.10.11:6379
        - 192.168.10.6:6379
      # 获取失败 最大重定向次数
      max-redirects: 3
    #如果用以前的jedis，可以把下面的lettuce换成jedis即可
    lettuce:
      pool:
        # 连接池最大连接数默认值为8
        max-active: 1000
        # 连接池最大阻塞时间（使用负值表示没有限制）默认值为-1
        max-wait: -1
        # 连接池中最大空闲连接数默认值为8
        max-idle: 10
        # 连接池中的最小空闲连接数，默认值为0
        min-idle: 10

